"""
Nested Builder example for a Composite sales organization.

Exercise statement:

Model a sales organization using the Composite and Builder patterns.

A sales organization consists of sales agents and sales groups. A sales
agent is a leaf in the tree and owns an individual commission. A sales
group is a composite and can contain both sales agents and other sales
groups.

The commission of a sales group is the sum of the commissions of all its
children.

The builder must support creating nested groups without maintaining a
mutable current node and without requiring navigation methods such as
up() or add_to_parent().

Nested groups are created by passing a callback to add_group(). The
callback receives a new builder that is scoped to the nested group.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Callable


class AbstractSalesUnit(ABC):

    @abstractmethod
    def get_commission(self) -> float:
        """Return the commission generated by this sales unit."""


class SalesAgent(AbstractSalesUnit):

    def __init__(self, name: str, commission: float) -> None:
        self.name = name
        self.commission = commission

    def get_commission(self) -> float:
        return self.commission


class SalesGroup(AbstractSalesUnit):

    def __init__(self, name: str) -> None:
        self.name = name
        self.children: list[AbstractSalesUnit] = []

    def add(self, unit: AbstractSalesUnit) -> None:
        self.children.append(unit)

    def get_commission(self) -> float:
        return sum(child.get_commission() for child in self.children)


SalesGroupBuilderCallback = Callable[["SalesGroupBuilder"], None]


class SalesGroupBuilder:

    def __init__(self, name: str) -> None:
        self._name = name
        self._children: list[AbstractSalesUnit] = []

    @classmethod
    def named(cls, name: str) -> SalesGroupBuilder:
        return cls(name)

    def add_agent(
        self,
        name: str,
        commission: float,
    ) -> SalesGroupBuilder:
        self._children.append(SalesAgent(name, commission))
        return self

    def add_group(
        self,
        name: str,
        configure: SalesGroupBuilderCallback,
    ) -> SalesGroupBuilder:
        nested_builder = SalesGroupBuilder.named(name)
        configure(nested_builder)

        nested_group = nested_builder.build()
        self._children.append(nested_group)

        return self

    def add_group_builder(
        self,
        builder: "SalesGroupBuilder",
    ) -> SalesGroupBuilder:
        # Attach a pre-configured (reusable) sub-tree built elsewhere.
        self._children.append(builder.build())
        return self

    def build(self) -> SalesGroup:
        group = SalesGroup(self._name)

        for child in self._children:
            group.add(child)

        return group


if __name__ == "__main__":
    # Reusable / external builder (built outside of the main tree definition)
    tabriz_branch_builder = (
        SalesGroupBuilder.named("Tabriz Branch")
        .add_agent("Regional Manager", 300)
        .add_agent("Local Agent", 200)
    )

    organization = (
        SalesGroupBuilder.named("Headquarters")
        .add_agent("CEO", 0)
        .add_group(
            "Tehran Branch",
            lambda tehran_builder: (
                tehran_builder
                .add_agent("Manager", 500)
                .add_group(
                    "North Sub-Branch",
                    lambda north_builder: (
                        north_builder
                        .add_agent("Ali", 100)
                        .add_agent("Reza", 150)
                    ),
                )
                .add_group(
                    "Central Sub-Branch",
                    lambda central_builder: (
                        central_builder
                        .add_agent("Maryam", 250)
                    ),
                )
            ),
        )
        .add_group_builder(tabriz_branch_builder)
        .build()
    )

    print(f"Total Commission: {organization.get_commission()}")
