"""
Nested Builder example for a Composite sales organization.

Exercise statement:

Model a sales organization using the Composite and Builder patterns.

A sales organization consists of sales agents and sales groups. A sales
agent is a leaf in the tree and owns an individual commission. A sales
group is a composite and can contain both sales agents and other sales
groups.

The commission of a sales group is the sum of the commissions of all its
children.

The builder must support creating nested groups without maintaining a
mutable current node and without requiring navigation methods such as
up() or add_to_parent().

Nested groups are created by passing a callback to add_group(). The
callback receives a new builder that is scoped to the nested group.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Callable


# Component: Base interface defining the common operation for leaves and composites.
class AbstractSalesUnit(ABC):

    @abstractmethod
    def get_commission(self) -> float:
        """Return the commission generated by this sales unit."""


# Leaf: Represents individual employees with their direct commission.
class SalesAgent(AbstractSalesUnit):

    def __init__(self, name: str, commission: float) -> None:
        self.name = name
        self.commission = commission

    def get_commission(self) -> float:
        return self.commission


# Composite: Represents a group/branch containing child units (agents or nested groups).
class SalesGroup(AbstractSalesUnit):

    def __init__(self, name: str) -> None:
        self.name = name
        self.children: list[AbstractSalesUnit] = []

    def add(self, unit: AbstractSalesUnit) -> None:
        self.children.append(unit)

    def get_commission(self) -> float:
        return sum(child.get_commission() for child in self.children)


# Callback type alias representing the nested configuration function received by add_group.
SalesGroupBuilderCallback = Callable[["SalesGroupBuilder"], None]


# Builder: Constructs hierarchical Composite trees using scoped builders and callbacks.
class SalesGroupBuilder:

    def __init__(self) -> None:
        self._children: list[AbstractSalesUnit] = []

    def add_agent(
        self,
        name: str,
        commission: float,
    ) -> SalesGroupBuilder:
        self._children.append(SalesAgent(name, commission))
        return self

    def add_group(
        self,
        name: str,
        configure: SalesGroupBuilderCallback,
    ) -> SalesGroupBuilder:
        # A fresh builder isolates the configuration of the nested group
        # from the builder that is constructing its parent group.
        nested_builder = SalesGroupBuilder()

        # The runtime leverages the Python call stack: entering the lambda pushes a new
        # frame with its own scoped builder, diving deeper into the tree.
        configure(nested_builder)

        # Once the callback finishes and unwinds (pops), the nested composite unit is built
        # and attached to the parent, effectively replacing mutable state and navigation (up()).
        nested_group = nested_builder.build(name)
        self._children.append(nested_group)

        return self

    def build(self, name: str) -> SalesGroup:
        group = SalesGroup(name)

        for child in self._children:
            group.add(child)

        return group


if __name__ == "__main__":
    # Client Code:
    # Uses a nested/recursive builder pattern with lambdas. Each lambda receives
    # an isolated sub-builder scoped strictly to that branch. This eliminates the need
    # for mutable traversal state (_currentNode) or navigation methods (e.g., up()).
    builder = SalesGroupBuilder()

    organization = (
        builder
        .add_agent("CEO", 0)
        .add_group(
            "Tehran Branch",
            lambda tehran_builder: (
                tehran_builder
                .add_agent("Manager", 500)
                .add_group(
                    "North Sub-Branch",
                    lambda north_builder: (
                        north_builder
                        .add_agent("Ali", 100)
                        .add_agent("Reza", 150)
                    ),
                )
                .add_group(
                    "Central Sub-Branch",
                    lambda central_builder: (
                        central_builder
                        .add_agent("Maryam", 250)
                    ),
                )
            ),
        )
        .add_group(
            "Isfahan Branch",
            lambda isfahan_builder: (
                isfahan_builder
                .add_agent("Hossein", 300)
                .add_agent("Zahra", 200)
            ),
        )
        .build("Headquarters")
    )

    print(f"Total Commission: {organization.get_commission()}")
