"""
Nested Builder and Template Prototype example for a Composite sales organization.

Exercise statement:

Model a sales organization using the Composite and Builder patterns.

A sales organization consists of sales agents and sales groups. A sales
agent is a leaf in the tree and owns an individual commission. A sales
group is a composite and can contain both sales agents and other sales
groups.

The commission of a sales group is the sum of the commissions of all its
children.

The builder supports:
1. Scoped nested group creation using closures/callbacks (leveraging the call stack).
2. Attaching pre-configured/reusable subtrees.
3. Prototype cloning (with_name) to reuse builder templates across multiple branches.
"""

from __future__ import annotations

import copy
from abc import ABC, abstractmethod
from collections.abc import Callable


class AbstractSalesUnit(ABC):

    @abstractmethod
    def get_commission(self) -> float:
        """Return the commission generated by this sales unit."""


class SalesAgent(AbstractSalesUnit):

    def __init__(self, name: str, commission: float) -> None:
        self.name = name
        self.commission = commission

    def get_commission(self) -> float:
        return self.commission


class SalesGroup(AbstractSalesUnit):

    def __init__(self, name: str) -> None:
        self.name = name
        self.children: list[AbstractSalesUnit] = []

    def add(self, unit: AbstractSalesUnit) -> None:
        self.children.append(unit)

    def get_commission(self) -> float:
        return sum(child.get_commission() for child in self.children)


SalesGroupBuilderCallback = Callable[["SalesGroupBuilder"], None]


class SalesGroupBuilder:

    def __init__(self, name: str) -> None:
        self._name = name
        self._children: list[AbstractSalesUnit] = []

    @classmethod
    def named(cls, name: str) -> SalesGroupBuilder:
        return cls(name)

    def with_name(self, new_name: str) -> SalesGroupBuilder:
        """Clone the builder configuration as a template under a new identity."""
        cloned_builder = copy.deepcopy(self)
        cloned_builder._name = new_name
        return cloned_builder

    def add_agent(
        self,
        name: str,
        commission: float,
    ) -> SalesGroupBuilder:
        self._children.append(SalesAgent(name, commission))
        return self

    def add_group(
        self,
        name: str,
        configure: SalesGroupBuilderCallback,
    ) -> SalesGroupBuilder:
        nested_builder = SalesGroupBuilder.named(name)
        configure(nested_builder)

        nested_group = nested_builder.build()
        self._children.append(nested_group)

        return self

    def add_group_builder(
        self,
        builder: SalesGroupBuilder,
    ) -> SalesGroupBuilder:
        self._children.append(builder.build())
        return self

    def build(self) -> SalesGroup:
        group = SalesGroup(self._name)

        for child in self._children:
            group.add(child)

        return group


if __name__ == "__main__":
    # 1. Prototype / Template Builder: Standard regional branch layout
    standard_branch_template = (
        SalesGroupBuilder.named("Standard Template")
        .add_agent("Regional Manager", 300)
        .add_agent("Local Agent", 200)
    )

    # 2. Main Tree construction combining Inline Lambdas and Template Clones
    organization = (
        SalesGroupBuilder.named("Headquarters")
        .add_agent("CEO", 0)
        .add_group(
            "Tehran Branch",
            lambda tehran_builder: (
                tehran_builder
                .add_agent("Manager", 500)
                .add_group(
                    "North Sub-Branch",
                    lambda north_builder: (
                        north_builder
                        .add_agent("Ali", 100)
                        .add_agent("Reza", 150)
                    ),
                )
                .add_group(
                    "Central Sub-Branch",
                    lambda central_builder: (
                        central_builder
                        .add_agent("Maryam", 250)
                    ),
                )
            ),
        )
        .add_group_builder(standard_branch_template.with_name("Tabriz Branch"))
        .add_group_builder(standard_branch_template.with_name("Shiraz Branch"))
        .build()
    )

    print(f"Total Commission: {organization.get_commission()}")
